version: '3'
services:
    doc_classification:
        build:
            dockerfile: ./doc_classification.dockerfile
            context: .
        image: py
        container_name: doc_classification
        ports: 
            - "5000:5000"
        network_mode: host
        depends_on: 
            - "localstack"
    doc_events:
        build:
            dockerfile: ./doc_events.dockerfile
            context: .
        image: doc_events
        container_name: doc_events
        network_mode: host
        depends_on: 
            - "localstack"
    doc_ocr:
        build:
            dockerfile: ./doc_ocr.dockerfile
            context: .
        image: doc_ocr
        container_name: doc_ocr
        ports: 
            - "8000:8000"
        network_mode: host
    localstack:
        image: localstack/localstack
        ports:
          - "4567-4584:4567-4584"
          - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
        environment:
          - SERVICES=kinesis
          - DEBUG=${DEBUG- }
          - DATA_DIR=${DATA_DIR- }
          - PORT_WEB_UI=${PORT_WEB_UI- }
          - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
          - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
          - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
          - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"
        network_mode: host
    doc_store:
        build:
            dockerfile: ./doc_store.dockerfile
            context: .
        image: doc_stores
        container_name: doc_stores
        ports: 
            - "8010:8010"
        network_mode: host     
